### ISSUE TITLE
Corey has 2x height wall jump

### ISSUE THREAD

**Issue by ConanODoyle** [portify/hotline-miami#1]
Small jump to leap over 2x high walls, could be scripted with crouching built in (eg default crouching) or just no crouch at all (so you cant go through windows)

**Comment by Crystalwarrior** [comment]
seems pretty redundant since Corey's ability is a dodge-slide (or roll once I bother to animate it)

**Comment by Crystalwarrior** [comment]
in fact we could simply combine the two in some way
